In [3]:
import pandas as pd
import torch.nn as nn
from tbnn.training_utils import early_stopped_tbnn_training_run
import torch
import matplotlib.pyplot as plt
import pickle
import torch.nn as nn
import tbnn.models as models
import tbnn.devices as devices
import tbnn.dataloaders as dataloaders
import tbnn.losses as losses
device = devices.get_device()
import numpy as np



In [4]:
dataset_params = {'file': '/home/ryley/WDK/ML/dataset/komegasst_fp_phll_duct.csv',
                  'test_set': ['case_1p2'],
                }

df = pd.read_csv(dataset_params['file'])

df = df[df['Case'].isin(['case_1p2'])]



In [20]:
Shat = np.empty((len(df),3,3))
Rhat = np.empty((len(df),3,3))
T10 = np.empty((len(df),3,3))
T7 = np.empty((len(df),3,3))

Shat[:,0,0] = df['komegasst_Shat_11']
Shat[:,0,1] = df['komegasst_Shat_12']
Shat[:,0,2] = df['komegasst_Shat_13']
Shat[:,1,1] = df['komegasst_Shat_22']
Shat[:,1,2] = df['komegasst_Shat_23']
Shat[:,2,2] = df['komegasst_Shat_33']
Shat[:,1,0] = Shat[:,0,1]
Shat[:,2,0] = Shat[:,0,2]
Shat[:,2,1] = Shat[:,1,2]

Rhat[:,0,0] = df['komegasst_Rhat_11']
Rhat[:,0,1] = df['komegasst_Rhat_12']
Rhat[:,0,2] = df['komegasst_Rhat_13']
Rhat[:,1,1] = df['komegasst_Rhat_22']
Rhat[:,1,2] = df['komegasst_Rhat_23']
Rhat[:,2,2] = df['komegasst_Rhat_33']
Rhat[:,1,0] = df['komegasst_Rhat_21']
Rhat[:,2,0] = df['komegasst_Rhat_31']
Rhat[:,2,1] = df['komegasst_Rhat_32']

T7[:,0,0] = df['komegasst_T7_11']
T7[:,0,1] = df['komegasst_T7_12']
T7[:,0,2] = df['komegasst_T7_13']
T7[:,1,1] = df['komegasst_T7_22']
T7[:,1,2] = df['komegasst_T7_23']
T7[:,2,2] = df['komegasst_T7_33']
T7[:,1,0] = df['komegasst_T7_21']
T7[:,2,0] = df['komegasst_T7_31']
T7[:,2,1] = df['komegasst_T7_32']

T10[:,0,0] = df['komegasst_T10_11']
T10[:,0,1] = df['komegasst_T10_12']
T10[:,0,2] = df['komegasst_T10_13']
T10[:,1,1] = df['komegasst_T10_22']
T10[:,1,2] = df['komegasst_T10_23']
T10[:,2,2] = df['komegasst_T10_33']
T10[:,1,0] = df['komegasst_T10_21']
T10[:,2,0] = df['komegasst_T10_31']
T10[:,2,1] = df['komegasst_T10_32']


T10_test = (Rhat @ Shat @ Shat @ Rhat @ Rhat) - (Rhat @ Rhat @ Shat @ Shat @ Rhat)
T7_test = (Rhat @ Shat @ Rhat @ Rhat) - (Rhat @ Rhat @ Shat @ Rhat)
print(T10[5000])
print(T10_test[5000])

print('Dataset:')
print(T7[5000])
print('Should be:')
print(T7_test[5000])
print(np.trace(T7_test[5000]))


[[ 3.79735e-11  1.42354e-11  9.79931e-31]
 [-1.87237e-06 -1.75991e-07  2.37319e-25]
 [-2.47395e-30 -1.04255e-29 -0.00000e+00]]
[[ 4.90259838e-11  1.83786902e-11 -3.19399030e-30]
 [ 1.83786902e-11 -4.90259838e-11 -1.34598840e-29]
 [-3.19399030e-30 -1.34598840e-29 -2.48113516e-48]]
Dataset:
[[-1.63420e-04 -6.12623e-05 -4.21715e-24]
 [-4.63512e-05 -4.35673e-06  5.87492e-24]
 [ 1.06467e-23  4.48663e-23  8.41000e-43]]
Should be:
[[-1.63419946e-04 -6.12623005e-05  1.06466343e-23]
 [-6.12623005e-05  1.63419946e-04  4.48662801e-23]
 [ 1.06466343e-23  4.48662801e-23  8.27045052e-42]]
8.270450520085095e-42
